image: Ubuntu1804

environment:
  matrix:
    - ARCH: i686
    - ARCH: armv7
    - ARCH: aarch64
  
install:
  - sh: |-
      curl -o llvm-mingw.tar.xz    -L https://github.com/mstorsjo/llvm-mingw/releases/download/20191230/llvm-mingw-20191230-ubuntu-16.04.tar.xz
      tar xJf llvm-mingw.tar.xz    || exit 1
      curl -o sdl.tar.gz           -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz
      tar xzf sdl.tar.gz           || exit 1
      curl -o zlib.tar.xz          -L https://www.zlib.net/zlib-1.2.11.tar.xz
      tar xJf zlib.tar.xz          || exit 1
      curl -o libpng.tar.xz        -L https://download.sourceforge.net/libpng/libpng-1.6.37.tar.xz
      tar xJf libpng.tar.xz        || exit 1
      curl -o libogg.tar.xz        -L http://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.xz
      tar xJf libogg.tar.xz        || exit 1
      curl -o libvorbis.tar.xz     -L http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.xz
      tar xJf libvorbis.tar.xz     || exit 1
      git clone https://github.com/exult/exult --depth 1
      sudo apt-get update -qq
      sudo apt-get install -y libtool-bin libsdl2-dev libogg-dev libvorbis-dev
      chmod +x build.sh
      
build_script:
  sh: ./build.sh

artifacts:
  - path: 'exult-windows*.zip'
    name: Exult

deploy:
  - release: v1.5.0git Build $(APPVEYOR_BUILD_NUMBER)
    description: Filezilla v1.5.0git Build $(APPVEYOR_BUILD_NUMBER)
    provider: GitHub
    artifact: /exult-windows.*\.zip/
    auth_token:
      secure: H8HAtJ5SrLHk1gW1eYZFcjtekn1rIW7a8GJsNC6Nftcql8wE0seZRtYqMnFoQLnr
    draft: true
